### ISSUE TITLE
Hello! How can I contribute?

### ISSUE THREAD

**Issue by taffarel55** [skgadi/umk#1]
I'd like to contribute in Documentation, Translation and Design of webpage, what do you think? :D

**Comment by skgadi** [comment]
Hi @taffarel55 , Thank you very much for showing interest. I am writing this message quickly to show my happiness towards your message. Let us have a video/audio call. I will explain the pending parts of the website. Also, you can come up with suggestions to improve the presentation part.

**Comment by taffarel55** [comment]
And I am writing this message quickly too to confirm my interest :smile:

Yeah, let's make a call!! I will contact you via email via the contact on your page to arrange the meeting. You can close this issue :smiley:
